// PPTX 对外类型别名，复用统一演示文稿模型并保留格式语义名称。
export type {
  BaseElement,
  ChartElement,
  GradientFill,
  GradientStop,
  GroupElement,
  ImageCrop,
  ImageElement,
  PresentationDocument as PptxDocument,
  ShadowStyle,
  ShapeElement,
  SlideBackground,
  SlideElement,
  SlideModel,
  TableCell,
  TableElement,
  TextBulletStyle,
  TextElement,
  TextParagraph,
  TextRun,
  TextStyle,
  ThemeModel,
  UnsupportedElement,
} from '../presentation/types';
